[phases.setup]
nixPkgs = ["python39"]

[phases.install]
cmds = ["echo 'No installation needed for static site'"]

[phases.build]
cmds = ["echo 'No build needed for static site'"]

[start]
cmd = "python -m http.server $PORT"
