[phases.setup]
nixPkgs = ["python39"]

[phases.install]
cmds = ["echo 'Static site - no dependencies to install'"]

[phases.build]
cmds = ["echo 'Static site - no build process needed'"]

[start]
cmd = "python -m http.server $PORT"
